version: '3.7'
services:
  test_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    ports:
      - '5433:5432'
    volumes: 
      - test_db:/var/lib/postgresql/data
volumes:
  test_db:
    driver: local