### Create user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "firstName": "Test2",
    "lastName": "User",
    "email": "bagr2@gmail.com",
    "password": "bagr2",
    "role": "Office"
}

### Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "bagr2@gmail.com",
    "password": "bagr2"
}

### Refresh token
POST http://localhost:4000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdyMkBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJUZXN0MiIsImxhc3ROYW1lIjoiVXNlciIsImRyaXZpbmdMaWNlbnNlIjpmYWxzZSwibm90ZSI6bnVsbCwiYWRtaW5Ob3RlIjpudWxsLCJyb2xlIjoiT2ZmaWNlIiwiYXZhdGFyVXJsIjpudWxsLCJhY3RpdmF0ZWRBY2NvdW50IjpmYWxzZSwiaWF0IjoxNzA0NDcxMzE1LCJleHAiOjE3MDU2ODA5MTV9.ePNLsj3eQnye15XubghmKpUfkzd7E4ltVH30JgTmP20"
}